FROM node:18-alpine AS builder
WORKDIR /app
COPY redis-like/src/package.json ./
RUN npm install --production
COPY redis-like/src/ ./

FROM node:18-alpine AS runtime
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app ./
EXPOSE 3000
CMD ["node", "index.js"] 