FROM node:18-alpine AS builder
WORKDIR /app
COPY kv/src/package.json ./
RUN npm install --production
COPY kv/src/ ./

FROM node:18-alpine AS runtime
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app ./
EXPOSE 3001
CMD ["node", "index.js"] 